name: CI da Calculadora Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessário para o badge de status

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Se você tivesse um arquivo requirements.txt, você o instalaria aqui com:
          # pip install -r requirements.txt

      - name: Test with unittest
        run: |
          python -m unittest discover

      - name: Update README with badge
        if: success() # Roda apenas se os testes passaram
        run: |
          # Configura o git com as credenciais do bot do GitHub Actions
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Adiciona o badge no início do README.md
          # A linha abaixo verifica se o badge já existe antes de adicionar
          grep -q "CI da Calculadora Python" README.md || sed -i '1i[![CI da Calculadora Python](https://github.com/${{ github.repository }}/actions/workflows/main.yaml/badge.svg)](https://github.com/${{ github.repository }}/actions/workflows/main.yaml)\n' README.md
          
          # Faz o commit e push das alterações no README.md
          git add README.md
          git commit -m "docs: Adiciona badge de status do CI" || echo "Nenhuma alteração no README"
          git push
